theme: jekyll-theme-cayman
title: From Biomedical Engineer to Data Scientist
description: A Journey to Dive Deep into Data
owner:
  name: Tracy Netemeyer
  email: tnetemeyer1@gmail.com
  linkedin: #tnetemeyer
  github: tnetemeyer
